<<<<<<< HEAD:Proyecto/models/model_config.yaml
bootstrap: true
max_depth: null
min_samples_leaf: 1
min_samples_split: 2
n_estimators: 100
random_state: 42
=======
model: RandomForestClassifier
params:
  n_estimators: 100
  random_state: 42
>>>>>>> 203a8178865fdf70dff0554c3b8c102453247f7e:Proyecto/models/1era ronda/model_config.yaml
